#!/usr/bin/env bash
set -ex

# If tag is not "latest" (it should be in format "<version>-latest") then replace "latest" to current date and push second image with date-based tag
if [[ $DOCKER_TAG != "latest" ]]
then
  DATE="$(date -u '+%F')"
  NEW_DOCKER_TAG="$(echo "$DOCKER_TAG" | cut -d '-' -f1)-${DATE}"
  NEW_IMAGE_NAME="${DOCKER_REPO}:${NEW_DOCKER_TAG}"

  docker tag "$IMAGE_NAME" "$NEW_IMAGE_NAME"
  docker push "$NEW_IMAGE_NAME"
fi
